services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: davi9090
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: workout_api-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:davi9090@db:5432/workout
    ports:
      - "8000:8000"
    volumes:
      - .:/workout_api

volumes:
  postgres_data:
